app/__init__.py
from flask import Flask
from config import Config
# import atexit

from app.extensions import scheduler


# from utils.jobs import clear_uploads_folder


def create_app(config_class=Config):
    # create and configure the app
    app = Flask(__name__)
    app.config.from_object(config_class)

    # Flask extensions init
    # scheduler.add_job(func=clear_uploads_folder, trigger="cron", hour='23', id='clear_uploads_folder')
    # scheduler.start()
    #
    # Shut down the scheduler when exiting the app
    # atexit.register(lambda: scheduler.shutdown())

    # Register blueprints
    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import os
from pathlib import Path
import numpy as np
from flask import render_template, request, current_app, flash
from werkzeug.utils import secure_filename

from app.main import bp
from utils.string_functions import is_ascii
from utils.image_editor_functions import add_text_to_image
from utils.steganographer import decode as steganographer_decode
from utils.steganographer import open_image as steganographer_open
from utils.steganographer import encode as steganographer_encode
from utils.steganographer import save_image as steganographer_save

files = [
    [0, '..%%ram=0dv"=er?"$50'],
    [1, '..%%deadfishproject-1.0%%.stg'],
    [2, '..%%secret.bin']
]


@bp.get('/index/')
@bp.get('/')
def index() -> str:
    return render_template('index.html', files=files)


@bp.get('/xfish/')
def xfish() -> str:
    flash('Nessun username trovato.')
    return render_template('xfish.html', username='<NO_NAME>', image='images/xfp_participation_pass.png')


@bp.post('/xfish/')
def xfish_post() -> str:
    username: str = request.form.get('username', '<NO_NAME>')[: 15]
    if username == '<NO_NAME>':
        flash('Nessun username trovato.')
        return render_template('xfish.html', username=username)
    else:
        flash('Congratulazioni per aver trovato questa pagina!')
        default_img: str = 'images/xfp_participation_pass.png'
        new_img: str = f"uploads/{username.lower().replace(' ', '_')}_participation_pass.png"
        add_text_to_image(Path(current_app.static_folder + '/' + default_img), username,
                          Path(current_app.static_folder + '/' + new_img))
        img = steganographer_open(Path(current_app.static_folder + '/' + new_img))
        enc = steganographer_encode(img, 'Se hai trovato questo easter egg sei proprio un boss.')
        steganographer_save(enc, Path(current_app.static_folder + '/' + new_img))
    return render_template('xfish.html', username=username, image=new_img)


@bp.get('/steganographer/')
def steganographer() -> str:
    flash("Caricare immagine con messaggio nascosto.")
    return render_template('steganographer.html', image='')


@bp.post('/steganographer/')
def steganographer_post() -> str:
    uploaded_img = request.files['uploaded-file']
    if not uploaded_img or uploaded_img.filename.find('.png') == -1:
        flash("Caricare immagine PNG.")
        return render_template('steganographer.html', image='')
    flash("Esito analisi immagine.")

    img_filename: str = secure_filename(uploaded_img.filename)
    img_path: Path = Path(os.path.join(current_app.config['UPLOAD_FOLDER'], img_filename))
    uploaded_img.save(img_path)
    image: np.ndarray = steganographer_open(img_path)
    message: str = steganographer_decode(image)
    if not is_ascii(message) or message == '':
        message = '<NO_MSG>'

    return render_template('steganographer.html', image=img_filename, hidden_message=message)

app/templates/base.html
<!DOCTYPE html>
<html lang="it">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"></script>
</head>
<style>
    @import url(https://fonts.googleapis.com/css?family=Raleway:100,200,300);

    .popout {
        animation: popout 0.5s ease;
    }

    @keyframes popout {
        from {
            transform: scale(0)
        }
        to {
            transform: scale(1)
        }
    }

    .xfishfont {
        font-family: 'Raleway', serif;
    }

    .chiller_font {
        font-family: 'chiller', serif;
    }

    .highlight {
        transition: all 0.2s ease;
        border: none;
    }

    .highlight:hover {
        transform: scale(1.01);
        box-shadow: 0 0 10px 2px rgb(0, 157, 255);
    }

    .zoom_icon {
        transition: all 0.25s ease;
    }

    .zoom_icon:hover {
        transform: scale(1.5);
        color: #00bbff;
    }

    #container {
        perspective: 130px;
        transition: all 0.2s ease;
    }

    .inner {
        transition: all 0.2s ease;
        box-shadow: 0 0 10px 2px rgb(0, 157, 255);
        border: 2px white solid;
    }

    .inner:hover {
        transform: scale(1.15);
        border-color: rgb(0, 157, 255);
        box-shadow: 0 0 10px 2px rgb(0, 157, 255);
    }

    #btn_rip.invisible {
        transition: all 0.8s ease;
    }

    #files_rip.visible {
        transition: all .5s ease;
    }

    .counter {
        text-align: center;
        font-weight: 100;
        font-size: 3em;
    }
</style>
<body data-bs-theme="dark"
      style="background-image: url({{ url_for('static', filename='images/background_img.png') }});
              background-repeat: no-repeat; background-attachment: fixed; background-position: center;">
<nav class="navbar bg-body-tertiary fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('static', filename='images/logo.png') }}" alt="Logo" style="width: 2.3rem"
                 class="d-inline-block align-text-top">
            OFish-Server
        </a>
    </div>
</nav>
{% block header %}{% endblock %}
{% block content %}{% endblock %}
</body>
<footer class="fixed-bottom text-secondary">
    <h6 class="text-end fs-6 fw-light">DeadFishProject-1.0 &nbsp;</h6>
</footer>
{% block script %}{% endblock %}
<script>
    const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
    const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))</script>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block title %}XFishProject - Home{% endblock %}
{% block header %}
    <div id="xfish" class="invisible">
        <form method="post" action="{{ url_for('main.xfish_post') }}" class="d-flex justify-content-center pt-5 mt-5">
            <div class="row g-3 align-items-center">
                <div class="col-auto xfishfont fs-1">
                    xfish
                </div>
                <div class="col-auto">
                    <label>
                        <input type="text" id="username" class="form-control rounded-0" name="username"
                               placeholder="Inserisci il tuo nome." required>
                    </label>
                </div>
                <div class="col-auto">
                    <input type="submit" class="btn btn-outline-light rounded-0">
                </div>
            </div>
        </form>
    </div>
{% endblock %}
{% block content %}
    <div id="index_content" class="xfishfont text-center">
        <h3 id="messages" style="margin-top: 6%"></h3>
        <div class="d-flex justify-content-center">
            <div id="progressbar" class="progress w-25 rounded-0" role="progressbar" style="height: 3px">
                <div id="progress-bar" class="progress-bar bg-info"></div>
            </div>
        </div>
        <div id="counter" class="counter visible"></div>
        <div class="d-flex justify-content-center">
            <ul id="files_rip" class="fs-6 text-start list-group invisible" style="width: 30%;">
                {% for file in files %}
                    <li class="list-group-item list-group-item-action">
                        <div class="row">
                            <div class="col-8">
                                <svg xmlns="http://www.w3.org/2000/svg" width="32" fill="#6ea8fe" class="bi bi-dot"
                                     viewBox="0 0 16 16">
                                    <path d="M8 9.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"></path>
                                </svg>
                                {{ file[1] }}
                            </div>
                            <div id="download{{ file[0] }}" class="col-4 d-flex justify-content-center my-auto">
                                {% if file[0] == 0 %}
                                    <small id="ripristinato{{ file[0] }}" class="text-danger invisible">Errore
                                        ripristino</small>
                                {% elif file[0] == 1 %}
                                    <a href="{{ url_for("main.steganographer") }}" class="zoom_icon">
                                        <svg id="ripristinato{{ file[0] }}" xmlns="http://www.w3.org/2000/svg"
                                             width="24" height="24" fill="currentColor" class="bi bi-globe2 invisible"
                                             viewBox="0 0 16 16">
                                            <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m7.5-6.923c-.67.204-1.335.82-1.887 1.855q-.215.403-.395.872c.705.157 1.472.257 2.282.287zM4.249 3.539q.214-.577.481-1.078a7 7 0 0 1 .597-.933A7 7 0 0 0 3.051 3.05q.544.277 1.198.49zM3.509 7.5c.036-1.07.188-2.087.436-3.008a9 9 0 0 1-1.565-.667A6.96 6.96 0 0 0 1.018 7.5zm1.4-2.741a12.3 12.3 0 0 0-.4 2.741H7.5V5.091c-.91-.03-1.783-.145-2.591-.332M8.5 5.09V7.5h2.99a12.3 12.3 0 0 0-.399-2.741c-.808.187-1.681.301-2.591.332zM4.51 8.5c.035.987.176 1.914.399 2.741A13.6 13.6 0 0 1 7.5 10.91V8.5zm3.99 0v2.409c.91.03 1.783.145 2.591.332.223-.827.364-1.754.4-2.741zm-3.282 3.696q.18.469.395.872c.552 1.035 1.218 1.65 1.887 1.855V11.91c-.81.03-1.577.13-2.282.287zm.11 2.276a7 7 0 0 1-.598-.933 9 9 0 0 1-.481-1.079 8.4 8.4 0 0 0-1.198.49 7 7 0 0 0 2.276 1.522zm-1.383-2.964A13.4 13.4 0 0 1 3.508 8.5h-2.49a6.96 6.96 0 0 0 1.362 3.675c.47-.258.995-.482 1.565-.667m6.728 2.964a7 7 0 0 0 2.275-1.521 8.4 8.4 0 0 0-1.197-.49 9 9 0 0 1-.481 1.078 7 7 0 0 1-.597.933M8.5 11.909v3.014c.67-.204 1.335-.82 1.887-1.855q.216-.403.395-.872A12.6 12.6 0 0 0 8.5 11.91zm3.555-.401c.57.185 1.095.409 1.565.667A6.96 6.96 0 0 0 14.982 8.5h-2.49a13.4 13.4 0 0 1-.437 3.008M14.982 7.5a6.96 6.96 0 0 0-1.362-3.675c-.47.258-.995.482-1.565.667.248.92.4 1.938.437 3.008zM11.27 2.461q.266.502.482 1.078a8.4 8.4 0 0 0 1.196-.49 7 7 0 0 0-2.275-1.52c.218.283.418.597.597.932m-.488 1.343a8 8 0 0 0-.395-.872C9.835 1.897 9.17 1.282 8.5 1.077V4.09c.81-.03 1.577-.13 2.282-.287z"></path>
                                        </svg>
                                    </a>
                                {% else %}
                                    <div id="progressbar{{ file[0] }}" class="progress w-100 rounded-0 invisible"
                                         role="progressbar" style="height: 20px">
                                        <div id="progress-bar{{ file[0] }}"
                                             class="progress-bar bg-info invisible"></div>
                                    </div>
                                {% endif %}
                            </div>

                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <br>
        <div class="d-flex justify-content-center">
            <button id="btn_rip" onclick="recover()"
                    type="button" class="btn btn-outline-light rounded-0 fs-5 w-25 invisible">Tentare il
                ripristino?
            </button>
        </div>
    </div>

{% endblock %}
{% block script %}
    <script>
        let typer_index = 0,
            txt = 'Ricerca di file danneggiati in corso...',
            speed = 50;
        let body = document.querySelector('body'),
            pbar = document.querySelector('#progressbar'),
            bar = document.querySelector('#progress-bar'),
            counter = document.querySelector('#counter'),
            btn_ripristino = document.querySelector('#btn_rip'),
            files = document.querySelector('#files_rip'),
            i = 0,
            show_counter = true,
            throttle = 0.875; // 0-1
        let xfish_set = false;

        function typeWriter(txt) {
            if (typer_index < txt.length) {
                document.getElementById("messages").innerHTML += txt.charAt(typer_index);
                typer_index++;
                setTimeout(typeWriter, speed, txt);
            }
        }

        function typeNewMessage(message) {
            document.getElementById("messages").innerHTML = '';
            typer_index = 0;
            typeWriter(message);
        }

        function draw() {
            if (i <= 100) {
                let r = Math.random();
                requestAnimationFrame(draw);
                bar.style.width = i + '%';
                if (show_counter)
                    counter.innerHTML = Math.ceil(i) + '%';
                if (r < throttle) { // Simulate d/l speed and uneven bitrate
                    i = i + r;
                }
            }
        }

        function showDownloadIcon() {
            bar.classList.toggle('invisible');
            pbar.classList.toggle('invisible');
            let download = document.querySelector('#download2');
            download.innerHTML = "<a href='{{ url_for('static', filename='files/secret.bin')}}' download><svg xmlns='http://www.w3.org/2000/svg' width='32' height='32' fill='white' class='bi bi-cloud-arrow-down zoom_icon' viewBox='0 0 16 16'><path fill-rule='evenodd' d='M7.646 10.854a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 9.293V5.5a.5.5 0 0 0-1 0v3.793L6.354 8.146a.5.5 0 1 0-.708.708z'/><path d='M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383m.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z'/></svg></a>";
        }

        function recover() {
            btn_ripristino.classList.toggle('invisible');
            setTimeout(typeNewMessage, 800, "Tentativo di ripristino dei file.");
            show_counter = true;
            let file0 = document.querySelector('#ripristinato0');
            let file1 = document.querySelector('#ripristinato1');
            file0.classList.toggle('invisible');
            file1.classList.toggle('invisible');
            bar = document.querySelector('#progress-bar2');
            counter = document.querySelector('#progress-bar2');
            pbar = document.querySelector('#progressbar2');
            bar.classList.toggle('invisible');
            pbar.classList.toggle('invisible');
            i = 0;
            draw();
            setTimeout(showDownloadIcon, 5000);
            setTimeout(typeNewMessage, 5000, "Ripristino concluso.");
        }

        function showResult() {
            pbar.classList.toggle('invisible');
            bar.classList.toggle('invisible');
            if (!counter.classList.contains('invisible')) {
                counter.classList.toggle('invisible');
            }
            btn_ripristino.classList.toggle('invisible');
            files.classList.toggle('invisible');
            typeNewMessage("Elenco file danneggiati.");
        }

        (function start() {
            typeWriter(txt);
            draw();
            setTimeout(showResult, 5000)
        })();

        function xfish(admin) {
            if (admin && !xfish_set) {
                xfish_set = true;
                let secret = document.querySelector('#xfish');
                secret.classList.toggle('invisible');
                let content = document.querySelector('#index_content');
                content.classList.toggle('invisible');
                if (!counter.classList.contains('invisible')) {
                    let counter = document.querySelector('#counter');
                    counter.classList.toggle('invisible');
                }
            }
        }
    </script>
{% endblock %}

app/templates/steganographer.html
{% extends 'base.html' %}
{% block title %}XFishProject - Find Message{% endblock %}
{% block header %}
    <div class="xfishfont">
        <h2 id="messages" class="text-center pt-5 mt-5"></h2>
    </div>
{% endblock %}
{% block content %}
    {% if image == '' %}
        <form method="post" enctype="multipart/form-data" action="{{ url_for('main.steganographer') }}"
              class="d-flex flex-column mt-5 w-100">
            <input class="form-control rounded-0 btn btn-outline-light mx-auto" type="file" style="width: 20%"
                   id="image_with_msg" accept=".png" name="uploaded-file" required>
            <button type="submit" class="btn btn-outline-light rounded-0 mx-auto mt-3" value="with hidden message"
                    style="width: 20%">
                <span class="fs-3">Analyze image</span><br>
                for hidden messages
            </button>
        </form>
    {% else %}
        <div class="d-flex flex-column">
            <div class="d-flex flex-column xfishfont">
                {% if hidden_message == '<NO_MSG>' %}
                    <div class="text-warning popout mt-5 d-flex justify-content-center">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             fill="currentColor" class="bi bi-exclamation-triangle"
                             viewBox="0 0 16 16">
                            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z"></path>
                            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z"></path>
                        </svg>
                        &nbsp;&nbsp;
                        <h3 class="border-bottom border-warning border-5">
                            Nessun messaggio ASCII trovato nell'immagine.
                        </h3>
                        &nbsp;&nbsp;
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             fill="currentColor" class="bi bi-exclamation-triangle"
                             viewBox="0 0 16 16">
                            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.15.15 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.2.2 0 0 1-.054.06.1.1 0 0 1-.066.017H1.146a.1.1 0 0 1-.066-.017.2.2 0 0 1-.054-.06.18.18 0 0 1 .002-.183L7.884 2.073a.15.15 0 0 1 .054-.057m1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767z"></path>
                            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0M7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0z"></path>
                        </svg>
                    </div>
                {% else %}
                    <div class="row w-75 mx-auto mt-4 border-bottom d-flex rounded-top bg-body-tertiary border border-bottom-0">
                        <div class="col-6 pt-3">
                            <p class="fs-4 mx-auto text-center fw-bold">
                                Immagine caricata
                            </p>
                        </div>
                        <div class="col-6 pt-3">
                            <p class="fs-4 mx-auto text-center fw-bold">
                                Testo trovato
                            </p>
                        </div>
                    </div>
                    <div class=" row w-75 mx-auto shadow-lg bg-body-tertiary p-3 pb-4 pt-4 rounded-bottom border">
                        <div class="col-6 d-flex flex-column border-end">
                            <img src="{{ url_for('static', filename='uploads/'+image) }}" alt="" style="height: 50vh"
                                 class="img-fluid mx-auto highlight">
                        </div>
                        <div class="col-6">
                            <div class="d-flex justify-content-between">
                                <div id="hidden_message" class="fs-5 text-wrap">
                                    {{ hidden_message }}
                                </div>
                                <a class="btn" onclick="saveToClipboard()" style="height: 5vh" id="copy_btn"
                                   data-bs-toggle="tooltip" data-bs-placement="top"
                                   data-bs-custom-class="custom-tooltip"
                                   data-bs-title="Copy to clipboard.">
                                    <svg id='clipboard_icon' xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                         fill="currentColor" class="bi bi-clipboard" viewBox="0 0 16 16">
                                        <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z"></path>
                                        <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z"></path>
                                    </svg>
                                </a>
                            </div>
                            <div class="text-left text-secondary align-bottom popout border-start border-5">
                                <div class="p-2 mt-4">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-info-circle" viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"></path>
                                        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0"></path>
                                    </svg>
                                    <small>Immagini senza testo nascosto analizzate con la tecnica del
                                        Least-Significant Bit non produrranno un messaggio sensato.</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock %}
{% block script %}
    <script>
        let typer_index = 0,
            txt = '{{ get_flashed_messages()[0] }}',
            speed = 50;

        (function typeWriter(txt) {
            if (typer_index < txt.length) {
                document.getElementById("messages").innerHTML += txt.charAt(typer_index);
                typer_index++;
                setTimeout(typeWriter, speed, txt);
            }
        })(txt);

        function typeNewMessage(message) {
            document.getElementById("messages").innerHTML = '';
            typer_index = 0;
            typeWriter(message);
        }

        function reset_clipboard_icon() {
            let copy_icon = document.querySelector('#clipboard_icon');
            copy_icon.innerHTML = "<svg id='clipboard_icon' xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-clipboard' viewBox='0 0 16 16'><path d='M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1z'></path><path d='M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0z'></path></svg>"
            const tooltip = bootstrap.Tooltip.getInstance('#copy_btn')
            tooltip.setContent({'.tooltip-inner': 'Copy to clipboard!'})
        }

        function saveToClipboard() {
            // Get the text field
            let copy_text = document.getElementById("hidden_message").innerText;
            navigator.clipboard.writeText(copy_text).then(() => {
                // Change button icon
                let copy_icon = document.querySelector('#clipboard_icon');
                copy_icon.innerHTML = "<svg id='clipboard_icon' xmlns='http://www.w3.org/2000/svg' width='16' height='16' fill='currentColor' class='bi bi-check2' viewBox='0 0 16 16'><path d='M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0'></path></svg>"
                const tooltip = bootstrap.Tooltip.getInstance('#copy_btn')
                tooltip.setContent({'.tooltip-inner': 'Copied!'})
                setTimeout(reset_clipboard_icon, 2000)
            });
        }
    </script>
{% endblock %}